### ISSUE TITLE
wtfwith ignored some packages

### ISSUE THREAD

**Issue by reklatsmasters** [jehy/wtfwith#4]
There is a more simple way to find installed packages - [`npm ls --json`](https://docs.npmjs.com/cli/ls)

Как вариант, можно сделать работу через пайп `npm ls --json --prod | wtfwith`. Останется только прочитать и выявить дубликаты.

А сейчас, игнорятся некоторые пакеты не пойму по какой логике. Например, вот тут wtfwith не покажет bluebird, а npm ls покажет.

```
$ npm ls --prod bluebird
backend@1.2.4 /app
├─┬ nodemailer-mailgun-transport@1.4.0
│ └─┬ consolidate@0.14.5
│   └── bluebird@3.5.1  deduped
├─┬ request-promise@4.2.2
│ └── bluebird@3.5.1 
├─┬ sequelize@4.37.7
│ ├── bluebird@3.5.1  deduped
│ └─┬ retry-as-promised@2.3.2
│   └── bluebird@3.5.1  deduped
└─┬ web3@1.0.0-beta.34
  └─┬ web3-bzz@1.0.0-beta.34
    └─┬ swarm-js@0.1.37
      ├── bluebird@3.5.1  deduped
      └─┬ tar.gz@1.0.7
        └── bluebird@2.11.0
```

К сожалению, npm ls  рисует слишком длинные деревья и реально дубликаты найти сложно. Будет круто, если wtfwith сможет компактно показывать реальные дубликаты любого уровня вложенности.

Спасибо в любом случае.

**Comment by jehy** [comment]
Кажется, у вас там только две версии блюбёрда - поэтому они и не показываются, по умолчанию показывается когда 3 и больше. Попробуйте сделать wtfwith bluebird --min 2.

**Comment by jehy** [comment]
Наверное, стоит в случае отсутствия аргумента не применять вообще ограничение.

**Comment by reklatsmasters** [comment]
@jehy по умолчанию показываются и дев, и прод версии, хотя я не указывал дев флаг. Кроме того, `--min 2` не работает, кажется.

![image](https://user-images.githubusercontent.com/2255752/39741173-381114ae-52b2-11e8-8a10-89d251ca0411.png)

Запускаю командой `npx wtfwith --min 2`

**Comment by jehy** [comment]
Это странно. А можете в качестве примера скинуть package.json и package lock? Можно, кстати, пулл реком с тестом на то, что должно получиться : )

Версия последняя? 1.0.16 или 1.0.17?

**Comment by reklatsmasters** [comment]
Да, последняя. Не уверен, что могу скинуть. Может позже на каких то своих open source  проектах протестирую.

**Comment by jehy** [comment]
`npm ls --json` это штука интересная, но она работает не на основании package.json/package-lock, а на основании анализа node_modules, что имхо не очевидно и в данном случае не совсем корректно - всё же часто бывает, что они не консистентны, и выбирать лучше явно лок файл.

**Comment by jehy** [comment]
Так, вроде поправил - была бага с парсингом консольных параметров, которая на юнитах не проявлялась, попробуйте 1.0.18.

**Comment by jehy** [comment]
Наверное, всё хорошо : )
